version: '3.8'
services:
  db2:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: engineering_11
      MYSQL_DATABASE: ThisAndThat
      MYSQL_ROOT_HOST: '%'
    volumes:
      - tatdat3:var/lib/mysql
    ports:
      - "33306:3306"
volumes:
  tatdat3: 
